name: felipe
description: writing about software engineering, leadership, and AI
author:
  name: Felipe Philipp
  x: felipeelias
  github: felipeelias
  linkedin: felipeelias
  bluesky: yerba.bsky.social
social:
  name: Felipe Philipp
  links:
    - https://x.com/felipeelias
    - https://www.linkedin.com/in/felipeelias
giscus:
  repo_id: MDEwOlJlcG9zaXRvcnk1MTMxODQ5NA==
  category_id: DIC_kwDOAw8O3s4C2o4_
url: https://felipeelias.github.io
logo: /assets/icon.jpg
baseurl:
timezone: Europe/Warsaw
pagination:
  enabled: true
  per_page: 10
  permalink: /page:num/
  sort_reverse: true
markdown: kramdown
kramdown:
  input: GFM
nav:
  - name: "About"
    url:  "/about"
  - name: "Archive"
    url:  "/archive"
  - name: "Tags"
    url:  "/tags"
  - name: "GitHub"
    url:  "https://github.com/felipeelias"
sass:
  sass_dir: _sass
  style: compressed
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      image: /assets/icon.jpg
plugins:
  - jekyll-paginate-v2
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap
exclude: [vendor]
jekyll-mentions:
  base_url: https://x.com
