name: this is fine
description: technical blog about programming and sowftware engineering
author:
  name: Felipe Philipp
  twitter: felipeelias
  github: felipeelias
  linkedin: felipeeliasphilipp
social:
  name: Felipe Philipp
  links:
    - https://twitter.com/felipeelias
    - https://www.linkedin.com/in/felipeeliasphilipp
    - https://plus.google.com/+FelipeEliasPhilipp
    - https://www.instagram.com/felipeelias
twitter:
  username: felipeelias
google-analytics:
  id: UA-73548507-1
disqus:
  id: thisisfine
url: https://felipeelias.github.io
logo: /assets/icon.jpg
baseurl:
timezone: Europe/Warsaw
paginate: 10
paginate_path: /page:num/
markdown: kramdown
kramdown:
  input: GFM
nav:
  - name: "About"
    url:  "/about"
  - name: "Projects"
    url:  "/projects"
  - name: "Archive"
    url:  "/archive"
  - name: "Tags"
    url:  "/tags"
  - name: "Github"
    url:  "https://github.com/felipeelias"
sass:
  sass_dir: _sass
  style: :compressed
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      image: /assets/icon.jpg
gems:
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap
exclude: [vendor]
jekyll-mentions:
  base_url: https://twitter.com
